- id: nac-validate
  name: Validate YAML files
  description: This hook performs syntactic and semantic validation of YAML files.
  entry: nac-validate
  language: python
  types: [file, yaml]
  exclude: (^\..+\.ya?ml$)|(^.*\/\.[^\/]+\.ya?ml$) # exclude hidden files and folders
